# Generated by Django 4.0.6 on 2022-07-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_profile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_bio',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
