# Generated by Django 4.0.6 on 2022-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True),
        ),
    ]
